defaults:
  - module/model: 4M
  - default
  - _self_

data:
  batch_size: 9830
  num_workers: 4
  dataset_path: datasets/data-25m-add

module:
  lr: 1e-3

trainer:
  pl:
    val_check_interval: 0.5

wandb:
  enabled: true
  project_name: "reason_net_add"