defaults:
  - module/model: 14M
  - default
  - _self_

data:
  batch_size: 8196
  num_workers: 4
  dataset_path: datasets/data-100m-all

trainer:
  pl:
    val_check_interval: 11000 # this means two time per epoch (0.9*10**8 / 8196)

module:
  lr: 5e-3
