defaults:
  - module/model: 14M
  - default
  - _self_

data:
  batch_size: 8196
  num_workers: 4
  dataset_path: datasets/data-20m-all

trainer:
  pl:
    val_check_interval: 0.5

module:
  lr: 5e-3
