defaults:
  - module/model: small
  - default
  - _self_

data:
  batch_size: 24576
  num_workers: 4
  dataset_path: datasets/data-20m-all

module:
  lr: 1e-3

trainer:
  pl:
    val_check_interval: 0.5

wandb:
  enabled: true
  project_name: "reason_net_all_small"