reason_mode: false

trainer:

  pl:
    devices: 1
    val_check_interval: 0.5
    max_epochs: 25

  save_dir: "lightning_logs"

  callbacks:
    norm_monitor:
      log_every_n_steps: 50
    perf_monitor:
      log_every_n_batchs: 50

wandb:
  enabled: true
  project_name: "reason_net"
